apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-resume-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-resume-app
  template:
    metadata:
      labels:
        app: my-resume-app
    spec:
      containers:
      - name: my-resume-app
        image: anuj2112/my-resume:v1
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: my-resume-app
spec:
  type: LoadBalancer
  ports:
  - port: 8081
  selector:
    app: my-resume-app