name: Docker Image CI

on:
  push:
    branches:
      - main
      - release
    tags:
      - "v0.0.0"
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-resume:$(date +%s)
    - name: list of docker images
      run: docker images
    - name: Login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    - name: pull image from docker hub
      run: docker pull anuj2112/my-resume:v1
    
#     - name: Create an incremental release
#       uses: aurestic/incrementarl-create-release@master
#       with:
#         flag_branch: false
#         message: Bump version
#         prev_tag: 'v'
#         update_odoo_module_version: true
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name:  ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
