name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-resume:$(date +%s)
    - name: list of docker images
      run: docker images
    - name: login to docker hub
      run: docker login -u ${{ secrets.USERNAME }} -p {{ secrets.PASSWORD }}
    - name: pull image from docker hub
      run: docker pull anuj2112/my-resume:v1
