name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-resume:$(date +%s)
    - name: list of docker images
      run: docker images
    - name: Login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    - name: pull image from docker hub
      run: docker pull anuj2112/my-resume:v1
    
    - name: Create tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: "0.*.*"
